version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: data_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
      TZ: Asia/Seoul
    ports:
      - "3308:3306"  # 외부 포트 3308을 MariaDB 내부 포트 3306에 매핑
    volumes:
      - C:/mariadb:/var/lib/mysql  # 데이터 볼륨 설정
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_batch_app
    environment:
      - TZ=Asia/Seoul
      - DB_URL=jdbc:mysql://mariadb:3306/data_db  # MariaDB 연결 URL을 환경 변수로 설정
      - DB_USERNAME=root
      - DB_PASSWORD=ENC(tNDykhELUbsWs+DpdUX4pQ==)
    ports:
      - "8091:8091"
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
