version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_batch_app
    networks:
      - my_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mariadb:3306/data_db?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1111
      - TZ=Asia/Seoul
    depends_on:
      - mariadb
    ports:
      - "8091:8091"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    networks:
      - my_network
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: data_db
      TZ: "Asia/Seoul"
    volumes:
      - C:/mariadb:/var/lib/mysql
    ports:
      - "3308:3306"  # 로컬 호스트의 3308 포트를 컨테이너의 3306 포트에 매핑

networks:
  my_network:
    driver: bridge
