spring:
  application:
    name: SpringBatch

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:15111:SECHUL
    username: DEX_LOCAL
    password: DEX_LOCAL11

  batch:
    job:
      enabled: false
      # name: firstJob
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-oracle.sql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      root: INFO
      org.springframework.batch: INFO

server:
  port: 8090
