spring:
  application:
    name: SpringBatch

  datasource-meta:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3307/meta_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1111

  datasource-data-otp:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3307/data_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1111

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
      schema: classpath:org/springframework/batch/core/schema-mysql.sql

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.example.springbatch.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      mybatis: DEBUG
    com:
      example:
        springbatch: DEBUG

server:
  port: 8080
