# default
spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/meta_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111
    hikari:
      maximum-pool-size: 10  # ?? ??? ? ??
      minimum-idle: 5  # ?? ?? ??? ?
      idle-timeout: 600000
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.example.springbatch.entity
  configuration:
    map-underscore-to-camel-case: true