# 로그 출력 방식: SLF4J (logback 등과 연동)
appender=com.p6spy.engine.spy.appender.Slf4JLogger

# 로그 포맷: 한 줄 출력
logMessageFormat=com.p6spy.engine.spy.appender.SingleLineFormat

# 제외할 로그 유형: result, batch, etc.
excludecategories=info,debug,result,batch

# 로그 레벨: debug
loglevel=debug
